###
POST http://localhost:1234/farmacia/cadastrar
content-type: application/json

{
    "nome": "Farmacia 1",
    "cnpj": "111"
}

###
GET http://localhost:1234/farmacia/buscar/111

###
GET http://localhost:1234/farmacia/listar

###
POST http://localhost:1234/farmacia/alterar
content-type: application/json

{
    "nome": "Farmacia 2",
    "cnpj": "555"
}

###
GET http://localhost:1234/farmacia/remover/111










###
POST http://localhost:1234/produto/cadastrar
content-type: application/json

{    
    "nome": "Sabonete",
    "codigo": "12345",
    "preco": 12,
    "descricao": "perfumaria",
    "cnpjFarmacia": "111"
}

###
GET http://localhost:1234/produto/buscar/111/54321

###
GET http://localhost:1234/produto/listar/111

###
POST http://localhost:1234/produto/alterar
content-type: application/json

{
    "nome": "Suco",
    "codigo": "54321",
    "preco": 27,
    "descricao": "bebidas",
    "cnpjFarmacia": "111"
}

###
GET http://localhost:1234/produto/remover/111/54321